#define FUNC_FUSE_LOOKUP        1
#define FUNC_FUSE_FORGET        2
#define FUNC_FUSE_GETATTR       3
#define FUNC_FUSE_SETATTR       4
#define FUNC_FUSE_READLINK      5
#define FUNC_FUSE_SYMLINK       6
#define FUNC_FUSE_MKNOD         8
#define FUNC_FUSE_MKDIR         9
#define FUNC_FUSE_UNLINK        10
#define FUNC_FUSE_RMDIR         11
#define FUNC_FUSE_RENAME        12
#define FUNC_FUSE_LINK          13
#define FUNC_FUSE_OPEN          14
#define FUNC_FUSE_READ          15
#define FUNC_FUSE_WRITE         16
#define FUNC_FUSE_STATFS        17
#define FUNC_FUSE_RELEASE       18
#define FUNC_FUSE_FSYNC         20
#define FUNC_FUSE_SETXATTR      21
#define FUNC_FUSE_GETXATTR      22
#define FUNC_FUSE_LISTXATTR     23
#define FUNC_FUSE_REMOVEXATTR   24
#define FUNC_FUSE_FLUSH         25
#define FUNC_FUSE_INIT          26
#define FUNC_FUSE_OPENDIR       27
#define FUNC_FUSE_READDIR       28
#define FUNC_FUSE_RELEASEDIR    29
#define FUNC_FUSE_FSYNCDIR      30
#define FUNC_FUSE_GETLK         31
#define FUNC_FUSE_SETLK         32
#define FUNC_FUSE_SETLKW        33
#define FUNC_FUSE_ACCESS        34
#define FUNC_FUSE_CREATE        35
#define FUNC_FUSE_INTERRUPT     36
#define FUNC_FUSE_BMAP          37
#define FUNC_FUSE_DESTROY       38
#define FUNC_FUSE_IOCTL         39
#define FUNC_FUSE_POLL          40
#define FUNC_FUSE_NOTIFY_REPLY  41
#define FUNC_FUSE_BATCH_FORGET  42
#define FUNC_FUSE_FALLOCATE     43
#define FUNC_FUSE_READDIRPLUS   44
#define FUNC_FUSE_RENAME2       45
#define FUNC_FUSE_LSEEK         46
